export const ASSETS = {
  SplashLogo: require("../../assets/images/SplashLogo.png"),
  OnboardingLogo: require("../../assets/images/OnboardingLogo.png"),
  loading: require("../../assets/lottie/loading.json"),
  onboardingLoading: require("../../assets/lottie/onboarding_loading.json"),
  carouselImg1: require("../../assets/images/CarouselScreen1.png"),
  carouselImg2: require("../../assets/images/CarouselScreen2.png"),
  carouselImg3: require("../../assets/images/CarouselScreen3.png"),
  OtpCodeImg: require("../../assets/images/OtpCodeImg.png"),
  EllipseImg: require("../../assets/images/Ellipse.png"),
  GateImg: require("../../assets/images/gate.png"),
  FloorImg: require("../../assets/images/gate.png"),
  SpotCarImg: require("../../assets/images/spot_car.png"),
  noBookmarks: require("../../assets/lottie/no_bookmaeks.json"),
  ParkingImg: "https://www.alpinme.com/files/parksmart.png",
  masterCardImg: require("../../assets/images/master_card.png"),
  SuccessfulPng: require("../../assets/images/SuccessfulPng.png"),
  transparentImg: require("../../assets/images/transparent_img.png"),
  CardImg: require("../../assets/images/Card.png"),
};
