import { ASSETS } from "./assets";



export const Slides = [
  {
    id: 1,
    title1: "Find Parking",
    title2: " Places\n",
    title3: "Around You Easily",
    description:
      "Ditch the hunt! Spot open spaces nearby, book 'em in a tap, and finally breathe easy. Parking made simple.",
    image: ASSETS.carouselImg1,
  },
  {
    id: 2,
    title1: "Book and Pay",
    title2: " Parking\n",
    title3: "Quickly & Safely",
    description:
      "Skip the meter mayhem. Secure your spot, pay with a click, and enjoy guilt-free parking. No sweat, just street.",
    image: ASSETS.carouselImg2,
  },
  {
    id: 3,
    title1: "Extend",
    title2: " Parking ",
    title3: "Time\nAs You Need It",
    description:
      "Running late? No stress. Extend your time in a flash and keep the good vibes rolling. Parking flex on point.",
    image: ASSETS.carouselImg3,
  },
];

export const floors = [
  {
    id: 1,
    title: "1st Floor",
    checked: "first",
    spots: [
      {
        id: 1,
        title1: "A01",
        status1: "booked",
        title2: "A02",
        status2: "available",
        title3: "A03",
        status3: "not available",
        title4: "A04",
        status4: "not available",
      },
      {
        id: 2,
        title1: "A05",
        status1: "not available",
        title2: "A06",
        status2: "booked",
        title3: "A07",
        status3: "available",
        title4: "A08",
        status4: "booked",
      },
      {
        id: 3,
        title1: "A09",
        status1: "booked",
        title2: "A10",
        status2: "booked",
        title3: "A11",
        status3: "booked",
        title4: "A12",
        status4: "not available",
      },
      {
        id: 4,
        title1: "A13",
        status1: "available",
        title2: "A14",
        status2: "available",
        title3: "A15",
        status3: "booked",
        title4: "A16",
        status4: "booked",
      },
      {
        id: 5,
        title1: "A17",
        status1: "booked",
        title2: "A18",
        status2: "booked",
        title3: "A19",
        status3: "booked",
        title4: "A20",
        status4: "booked",
      },
      {
        id: 6,
        title1: "A21",
        status1: "available",
        title2: "A22",
        status2: "available",
        title3: "A23",
        status3: "available",
        title4: "A24",
        status4: "available",
      },
      {
        id: 7,
        title1: "A25",
        status1: "not available",
        title2: "A26",
        status2: "not available",
        title3: "A27",
        status3: "not available",
        title4: "A28",
        status4: "not available",
      },
      {
        id: 8,
        title1: "A29",
        status1: "not available",
        title2: "A30",
        status2: "not available",
        title3: "A31",
        status3: "not available",
        title4: "A32",
        status4: "not available",
      },
    ],
  },
  {
    id: 2,
    title: "2nd Floor",
    checked: "second",
    spots: [
      {
        id: 1,
        title1: "B01",
        status1: "booked",
        title2: "B02",
        status2: "available",
        title3: "B03",
        status3: "not available",
        title4: "B04",
        status4: "not available",
      },
      {
        id: 2,
        title1: "B05",
        status1: "not available",
        title2: "B06",
        status2: "booked",
        title3: "B07",
        status3: "available",
        title4: "B08",
        status4: "booked",
      },
      {
        id: 3,
        title1: "B09",
        status1: "booked",
        title2: "B10",
        status2: "booked",
        title3: "B11",
        status3: "booked",
        title4: "B12",
        status4: "not available",
      },
      {
        id: 4,
        title1: "B13",
        status1: "available",
        title2: "B14",
        status2: "available",
        title3: "B15",
        status3: "booked",
        title4: "B16",
        status4: "booked",
      },
      {
        id: 5,
        title1: "B17",
        status1: "booked",
        title2: "B18",
        status2: "booked",
        title3: "B19",
        status3: "booked",
        title4: "B20",
        status4: "booked",
      },
      {
        id: 6,
        title1: "B21",
        status1: "available",
        title2: "B22",
        status2: "available",
        title3: "B23",
        status3: "available",
        title4: "B24",
        status4: "available",
      },
      {
        id: 7,
        title1: "B25",
        status1: "not available",
        title2: "B26",
        status2: "not available",
        title3: "B27",
        status3: "not available",
        title4: "B28",
        status4: "not available",
      },
      {
        id: 8,
        title1: "B29",
        status1: "not available",
        title2: "B30",
        status2: "available",
        title3: "B31",
        status3: "available",
        title4: "B32",
        status4: "not available",
      },
    ],
  },
  {
    id: 3,
    title: "3rd Floor",
    checked: "third",
    spots: [
      {
        id: 1,
        title1: "C01",
        status1: "booked",
        title2: "C02",
        status2: "available",
        title3: "C03",
        status3: "not available",
        title4: "C04",
        status4: "not available",
      },
      {
        id: 2,
        title1: "C05",
        status1: "not available",
        title2: "C06",
        status2: "booked",
        title3: "C07",
        status3: "available",
        title4: "C08",
        status4: "booked",
      },
      {
        id: 3,
        title1: "C09",
        status1: "booked",
        title2: "C10",
        status2: "booked",
        title3: "C11",
        status3: "booked",
        title4: "C12",
        status4: "not available",
      },
      {
        id: 4,
        title1: "C13",
        status1: "available",
        title2: "C14",
        status2: "available",
        title3: "C15",
        status3: "booked",
        title4: "C16",
        status4: "booked",
      },
      {
        id: 5,
        title1: "C17",
        status1: "booked",
        title2: "C18",
        status2: "booked",
        title3: "C19",
        status3: "booked",
        title4: "C20",
        status4: "booked",
      },
      {
        id: 6,
        title1: "C21",
        status1: "available",
        title2: "C22",
        status2: "available",
        title3: "C23",
        status3: "available",
        title4: "C24",
        status4: "available",
      },
      {
        id: 7,
        title1: "C25",
        status1: "not available",
        title2: "C26",
        status2: "not available",
        title3: "C27",
        status3: "not available",
        title4: "C28",
        status4: "not available",
      },
      {
        id: 8,
        title1: "C29",
        status1: "booked",
        title2: "C30",
        status2: "booked",
        title3: "C31",
        status3: "booked",
        title4: "C32",
        status4: "not available",
      },
    ],
  },
];

export const PopularParkingData = [
  {
    id: "A1",
    address: "1342 Antonietta Rest",
    title: "North Grove Way",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Popular",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "A2",
    address: "1342 Antonietta Rest",
    title: "Blake Valley",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Popular",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "A3",
    address: "1342 Antonietta Rest",
    title: "Hopton Hollies",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Popular",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "A4",
    address: "1342 Antonietta Rest",
    title: "Oak Tree Parc",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Popular",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "A5",
    address: "1342 Antonietta Rest",
    title: "Edward Brambles",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Popular",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "A6",
    address: "1342 Antonietta Rest",
    title: "De Lara Way",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Popular",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "A7",
    address: "1342 Antonietta Rest",
    title: "Campion Cottages",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Popular",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 5,
        title: "Gate 5",
        checked: "fifth",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 6,
        title: "Gate 6",
        checked: "sixth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
];

export const NearbyParkingData = [
  {
    id: "B1",
    address: "1342 Antonietta Rest",
    title: "North Grove Way",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Nearby",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "B2",
    address: "1342 Antonietta Rest",
    title: "Blake Valley",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Nearby",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "B3",
    address: "1342 Antonietta Rest",
    title: "Hopton Hollies",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Nearby",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "B4",
    address: "1342 Antonietta Rest",
    title: "Oak Tree Parc",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Nearby",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "B5",
    address: "1342 Antonietta Rest",
    title: "Edward Brambles",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Nearby",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "B6",
    address: "1342 Antonietta Rest",
    title: "De Lara Way",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Nearby",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    id: "B7",
    address: "1342 Antonietta Rest",
    title: "Campion Cottages",
    imageUrl: ASSETS.ParkingImg,
    currency: "$",
    cost: "10.00",
    rating: "4.9",
    estimatedTime: "5",
    availableSpots: "28",
    liked: false,
    saved: false,
    type: "Nearby",
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 5,
        title: "Gate 5",
        checked: "fifth",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 6,
        title: "Gate 6",
        checked: "sixth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
];

export const parkingData = [
  {
    name: "Campion Cottages",
    address: "1342 Antonietta Rest",
    id: "0",
    distance: 1,
    cost: 10.0,
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 5,
        title: "Gate 5",
        checked: "fifth",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 6,
        title: "Gate 6",
        checked: "sixth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    name: "De Lara Way",
    address: "86598 Kuhlman Keys Apt. 279",
    id: "1",
    distance: 1.3,
    cost: 2.48,
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    name: "Edward Brambles",
    address: "72571 Kilback Forks",
    id: "2",
    distance: 2.2,
    cost: 3.5,
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    name: "Oak Tree Parc",
    address: "53952 Hirthe Harbor Apt. 594",
    id: "3",
    distance: 4,
    cost: 4.0,
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    name: "Hopton Hollies",
    address: "21290 Gutmann Land",
    id: "4",
    distance: 0.5,
    cost: 8.0,
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    name: "Blake Valley",
    address: "632 Hailie Park",
    id: "5",
    distance: 3,
    cost: 6.0,
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 4,
        title: "Gate 4",
        checked: "fourth",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
  {
    name: "North Grove Way",
    address: "215 Sage Alley",
    id: "6",
    distance: 2,
    cost: 13.0,
    floors: floors,
    gates: [
      {
        id: 1,
        title: "1st Gate",
        checked: "first",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 2,
        title: "2nd Gate",
        checked: "second",
        imageUrl: ASSETS.GateImg,
      },
      {
        id: 3,
        title: "3rd Gate",
        checked: "third",
        imageUrl: ASSETS.GateImg,
      },
    ],
  },
];

export const ParkingSpots = [
  [
    {
      title: "A01",
      status: "not available",
    },
    {
      title: "A02",
      status: "booked",
    },
    {
      title: "A03",
      status: "available",
    },
    {
      title: "A04",
      status: "available",
    },
  ],
  [
    {
      title: "A05",
      status: "available",
    },
    {
      title: "A06",
      status: "not available",
    },
    {
      title: "A07",
      status: "booked",
    },
    {
      title: "A08",
      status: "not available",
    },
  ],

  [
    {
      title: "A09",
      status: "not available",
    },
    {
      title: "A10",
      status: "booked",
    },
    {
      title: "A11",
      status: "not available",
    },
    {
      title: "A12",
      status: "not available",
    },
  ],
  [
    {
      title: "A13",
      status: "booked",
    },
    {
      title: "A14",
      status: "booked",
    },
    {
      title: "A15",
      status: "available",
    },
    {
      title: "A16",
      status: "available",
    },
  ],
  [
    {
      title: "A17",
      status: "not available",
    },
    {
      title: "A18",
      status: "not available",
    },
    {
      title: "A19",
      status: "not available",
    },
    {
      title: "A20",
      status: "available",
    },
  ],
];

export const ParkingStates = [
  {
    id: 1,
    title: "Ongoing",
    checked: "Ongoing",
  },
  {
    id: 2,
    title: "Completed",
    checked: "Completed",
  },
  {
    id: 3,
    title: "Cancelled",
    checked: "Cancelled",
  },
];


export const PaymentMethods = [
  {
    id: 1,
    title: "Paypal",
    checked: "paypal",
  },
  {
    id: 2,
    title: "Google Pay",
    checked: "googlePay",
  },
  {
    id: 3,
    title: "Apple Pay",
    checked: "applePay",
  },
  {
    id: 4,
    title: "•••• •••• •••• •••• 4679",
    checked: "masterCard",
  },
];
